<a href="https://colab.research.google.com/github/utkarshanand336/Data-Science-Projects/blob/main/ML_classification_KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/ML/DataSet/iris.csv')

In [ ]:
df

sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [ ]:
X=df.iloc[:,:-1]
y=df.iloc[:,4]

In [ ]:
print(X)
for i in y:
  print(i)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=2)

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler=StandardScaler()

In [ ]:
scaler.fit(X_train)

StandardScaler()

In [ ]:
X_train=scaler.transform(X_train)
X_test=scaler.transform(X_test)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=3)
classifier.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [ ]:
y_predict=classifier.predict(X_test)
y_predict

array(['Setosa', 'Setosa', 'Virginica', 'Setosa', 'Setosa', 'Virginica',
       'Setosa', 'Virginica', 'Virginica', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Versicolor', 'Versicolor', 'Setosa',
       'Versicolor', 'Virginica', 'Versicolor', 'Versicolor',
       'Versicolor', 'Virginica', 'Versicolor', 'Versicolor', 'Setosa',
       'Setosa', 'Virginica', 'Setosa', 'Virginica'], dtype=object)

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [ ]:
print(classification_report(y_test,y_predict))
print(confusion_matrix(y_test,y_predict))
print(accuracy_score(y_test,y_predict))

              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00        14
  Versicolor       1.00      1.00      1.00         8
   Virginica       1.00      1.00      1.00         8

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

[[14  0  0]
 [ 0  8  0]
 [ 0  0  8]]
1.0


In [ ]:
print(confusion_matrix(y_test,y_predict))

[[14  0  0]
 [ 0  8  0]
 [ 0  0  8]]


In [ ]:
print(y_predict)

['Setosa' 'Setosa' 'Virginica' 'Setosa' 'Setosa' 'Virginica' 'Setosa'
 'Virginica' 'Virginica' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa'
 'Versicolor' 'Versicolor' 'Setosa' 'Versicolor' 'Virginica' 'Versicolor'
 'Versicolor' 'Versicolor' 'Virginica' 'Versicolor' 'Versicolor' 'Setosa'
 'Setosa' 'Virginica' 'Setosa' 'Virginica']


In [ ]:
print(X_test)

[[-1.60187983  0.76525353 -1.41863824 -1.26098371]
 [-1.60187983  0.09002983 -1.36100907 -1.39453891]
 [-0.24383142 -1.26041758  0.65601213  1.00945474]
 [-1.35496194 -0.13504474 -1.41863824 -1.52809411]
 [-1.35496194  0.76525353 -1.13049236 -1.39453891]
 [ 1.60805278 -0.13504474  1.11704555  0.47523393]
 [-1.10804404 -0.13504474 -1.30337989 -1.39453891]
 [ 0.99075804 -1.26041758  1.11704555  0.74234434]
 [ 0.6203812  -0.58519388  1.0017872   1.14300994]
 [-1.35496194 -0.13504474 -1.41863824 -1.26098371]
 [-0.7376672   1.44047724 -1.36100907 -1.39453891]
 [-1.84879772  0.3151044  -1.47626742 -1.39453891]
 [-1.10804404  0.3151044  -1.5338966  -1.39453891]
 [-0.61420826  1.89062637 -1.24575071 -1.1274285 ]
 [ 0.12654542  0.76525353  0.36786625  0.47523393]
 [ 0.74384015 -0.58519388  0.42549542  0.34167873]
 [-1.72533877 -1.71056672 -1.47626742 -1.26098371]
 [-0.24383142 -0.36011931  0.19497872  0.07456832]
 [ 0.99075804  0.54017896  1.05941637  1.67723075]
 [-0.49074931 -1.26041758  0.07